### ISSUE TITLE
Unmet build dependencies: debhelper (>= 9)

### ISSUE THREAD

**Issue by thunderboympm** [lcgamboa/tty0tty#10]
it is saying that there are unmet build dependencies, here I am sending the errors I got
<pre>dpkg-buildpackage
<b>dpkg-buildpackage: </b><font color="#26A269">info</font>: source package tty0tty
<b>dpkg-buildpackage: </b><font color="#26A269">info</font>: source version 1.4-0
<b>dpkg-buildpackage: </b><font color="#26A269">info</font>: source distribution stretch
<b>dpkg-buildpackage: </b><font color="#26A269">info</font>: source changed by Pascal Jean &lt;pascal.jean@piduino.org&gt;
<b>dpkg-buildpackage: </b><font color="#26A269">info</font>: host architecture amd64
<font color="#A347BA"><b> dpkg-source --before-build .</b></font>
<b>dpkg-checkbuilddeps: </b><font color="#C01C28"><b>error</b></font>: Unmet build dependencies: debhelper (&gt;= 9)
<b>dpkg-buildpackage: </b><font color="#A2734C"><b>warning</b></font>: build dependencies/conflicts unsatisfied; aborting
<b>dpkg-buildpackage: </b><font color="#A2734C"><b>warning</b></font>: (Use -d flag to override.)
</pre>

**Comment by lcgamboa** [comment]
Did you follow the Readme.md installation instructions? 
Apparently you don't have debhelper installed.
 Try running the `dpkg -l debhelper`  command to verify.
