### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by huseyinkozan** [lcgamboa/tty0tty#14]
Hi,

I am getting `Resource temporarily unavailable` after opening the port, and it closes at kernels 5.15, 5.19, 6.3.5, 6.4.0rc2. But it works at kernel 6.1.31.

I had opened an issue to freemed/tty0tty/issues/45, too.

**Comment by lcgamboa** [comment]
Hi @huseyinkozan ,

the freemed fork driver is different from the one I keep. 
Could you confirm that this issue occurs using the driver from this repository?
As far as I remember this problem was fixed a long time ago in the code of this repository.

**Comment by huseyinkozan** [comment]
Hi @lcgamboa,

Sorry for the disturb. I tried these kernels one by one, and all works.
* 5.15.114
* 6.1.31
* 6.3.5
* 6.4.0rc2

Also, thanks for the great job.
