### ISSUE TITLE
tty0tty and secure boot

### ISSUE THREAD

**Issue by RealBC** [lcgamboa/tty0tty#15]
Hello,

Fisrt congratulation for this very useful program avoiding cables plugged. 
I used it on V1.2 on a debian VM and it worsks perfectly as expected.
However i tried the V1.4 on Ubuntu Jammy 22.04 and I've some proplems especially with the secure boot with a "real computer".

`modprob tty0tty
ERROR could not inset 'tty0tty' key was rejected by service
make: *** [Makefile:38 : Install] Erreur 1`

I tried to follow and adapt the debian advice https://wiki.debian.org/SecureBoot but without any success

I certainly miss something.
Does anaybody have a clear procedure to follow to manage this case ?

Thanks in advance for your advice.

**Comment by lcgamboa** [comment]
Hi @RealBC ,

I use secure boot on Debian testing with the tty0tty module (using dkms) with no problems. 
I followed the steps from the Debian [secure boot wiki](https://wiki.debian.org/SecureBoot#MOK_-_Machine_Owner_Key).
Check all the steps in the wiki and see the error messages. As far as I remember there are 3 steps that I need to change to work on my computer.
