### ISSUE TITLE
How to make a virtual tty (tty0tty) look like a real serial port?

### ISSUE THREAD

**Issue by moefear85** [lcgamboa/tty0tty#21]
The virtual serial ports appear as `/dev/tntX` where X is an integer between 0 and 7. Problem is, many apps require "real" serial ports, such as *Lightburn*. So `/dev/tntX` devices don't show up in the list of selectable serial ports. Can this be remedied? Real serial ports show up as:
```
crw-rw----+ 1 root plugdev 188, 0 Mär 20 18:02 /dev/ttyUSB0
crw-rw----+ 1 root plugdev 188, 1 Mär 20 18:02 /dev/ttyUSB1
...
```
whereas the virtual ones as:
```
crw-rw-rw- 1 root dialout 234, 0 Mär 20 12:46 /dev/tnt0
crw-rw-rw- 1 root dialout 234, 1 Mär 20 12:46 /dev/tnt1
crw-rw-rw- 1 root dialout 234, 2 Mär 20 12:46 /dev/tnt2
...
```
I suspect it has to do with the major device numbers being different. Is there some way to change/spoof this, perhaps using `ln` or `mknod`, possibly involving `/sys` or `/proc`?

**Comment by lcgamboa** [comment]
It's possible to edit the "/etc/udev/rules.d/99-tty0tty.rules" file and create permanent symbolic names with the parameter SYMLINK:
```
SUBSYSTEM=="tty", KERNEL=="tnt0", GROUP="dialout", MODE="0660", SYMLINK+="ttyUSB10"
```
But this solution doesn't work with all software. Some software only detects serial ports that have an associated USB descriptor. There is no standardization on how to detect a serial port in Linux.

**Comment by moefear85** [comment]
I tried your suggestion, it works for python. calling `serial.tools.list_ports.comports()` now shows the virtual ports through their symlinks, before they never appeared. Unfortunately, it didn't work for LightBurn, even though the latter detects two `/dev/ttyS*` where * is a number on my system, so it isn't that it specifically expects USB devices.

Thus I have to ask, isn't there a standard C function that lists serial devices, or how does python do it? What are the methods of detecting serial ports in linux? I mean, it isn't like the the software (in this case LightBurn) is calling some master function then filtering out the results, otherwise one could then call that master function outside of lightburn and then get all serial devices, even "/dev/ttyX" where X is a number. I'm guessing a brute-force method would be to search for all device nodes under /"dev/tty*" where * is a wildcard, then filter the results. Do you think this is what LightBurn is doing? Or is there some other syscall that can query for possible devices?

Perhaps there is some cli or C call to the udev subsystem that returns a set of devices depending on filters passed as arguments? Or do some packages perhaps to into /etc/udev and scour the entries there?

**Comment by moefear85** [comment]
I think it is better to ask the following:

I assume that whether or not a piece of software sees or accepts a specific device or not, does not depend on the name or id of the driver handling it.  I also think it is possible for multiple drivers to register to handle any specific device major/minor number. I also assume the problem here, whatever the specifics, boils down to a different major number than what LightBurn is expecting.

Given all this, is it possible to modify the source someway to make it use the same major number as ttyS or ttyUSB or ttyACM devices, and then tell the system in some configuration file to specifically use tty0tty driver for the tnt devices once the system detects them on boot? Perhaps that would permanently resolve this issue for all software then so that the power of tty0tty can be fully utilized. ssniffer is a great piece of software to see the invisible and troubleshoot some problem (such as what I am having with LightBurn), but isn't usable in many cases if the software doesn't even see the virtual port.

**Comment by lcgamboa** [comment]
Hi @moefear85 ,

As I said previously, there is no standard to detect serial ports on Linux, all the ones you described above are valid. A common pattern is to try to use the TIOCGSERIAL ioctl on the device to find out if it is a serial port. Although tty0tty has ioctl implemented, it does not work on newer kernels as described [here](https://lore.kernel.org/lkml/20180913024049.24567-5-viro@ZenIV.linux.org.uk/). I corrected it in commit bca8008, and tested it with the `setserial` program that uses this method and now it is working as it should. Could you check if your program works after this fix?

**Comment by lcgamboa** [comment]
I tested with _Lightburn_ and the problem was not resolved. _Lightburn_ uses Qt, and Qt supports detecting tty0tty ports as can be seen in the[ code to list serial ports](https://code.qt.io/cgit/qt/qtserialport.git/tree/src/serialport/qserialportinfo_unix.cpp). I have some applications that use Qt and they detect `tntx` ports without any problems. Either _Lightburn_ uses an old version of Qt or implements its own serial port search function.

**Comment by moefear85** [comment]
sorry for the delay, I was just about to test it... thank you very much for your insight and time. I won't bother you further then, I'll consider this resolved. I'll try to use a hardware-based sniffing solution to work with lightburn or find some other software, as it isn't open source.

**Comment by lcgamboa** [comment]
Hi @moefear85 ,

I did some investigation on Lightburn. Opening the program in a terminal and enabling the log option (Help -> Enable debug log) you can see that the `tnt` ports are detected, but they appear with "Valid Candidate: false" and only the `tty` ports appear with true.
I edited the executable with `vbindiff` and replaced the two occurrences of the string "tty" with "tnt" and the program detected the ports without problems.
In `vbindiff` search in hex for `74 74 79 00` and replace for `74 6E 74 00`.

Happy Hacking.

![lightb](https://github.com/lcgamboa/tty0tty/assets/13749258/8ee638d7-93af-4132-984f-9d2744cf096f)

**Comment by moefear85** [comment]
wow! you are truly an expert! I have alot to learn...
