### ISSUE TITLE
Ubuntu 20.04 modprobe: ERROR: could not insert 'tty0tty': Operation not permitted

### ISSUE THREAD

**Issue by MAKCOFF** [lcgamboa/tty0tty#8]
Sorry, but i have a problem with install. If you know, help please.

maksim@hp-pc:~/tty0tty/module$ sudo make install
make -C /lib/modules/5.13.0-27-generic/build M=/home/maksim/tty0tty/module modules
make[1]: вход в каталог «/usr/src/linux-headers-5.13.0-27-generic»
make[1]: выход из каталога «/usr/src/linux-headers-5.13.0-27-generic»
echo "tty0tty" > /etc/modules-load.d/tty0tty.conf
cp 99-tty0tty.rules  /etc/udev/rules.d/
service udev reload
chown root:root /etc/udev/rules.d/99-tty0tty.rules
mkdir -p /lib/modules/5.13.0-27-generic/misc/
cp -v tty0tty.ko /lib/modules/5.13.0-27-generic/misc/
'tty0tty.ko' -> '/lib/modules/5.13.0-27-generic/misc/tty0tty.ko'
depmod
modprobe tty0tty
modprobe: ERROR: could not insert 'tty0tty': Operation not permitted
make: *** [Makefile:38: install] Ошибка 1

maksim@hp-pc:~/tty0tty/module$ hostnamectl
   Static hostname: hp-pc
   Pretty hostname: HP-PC
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: 3ed361a1ac9747da880fc9a3e69eb828
           Boot ID: 52ea70a69fd24b51825e9a874544f713
  Operating System: Ubuntu 20.04.3 LTS
            Kernel: Linux 5.13.0-27-generic
      Architecture: x86-64

**Comment by MAKCOFF** [comment]
I think it has something to do with updating the Linux security policy. But how do you solve it...

**Comment by lcgamboa** [comment]
Hi @MAKCOFF. 

Apparently this is a UEFI enabled secure boot issue. Take a look at the link: https://askubuntu.com/questions/1114867/operation-not-permitted-when-trying-to-modprobe-xpad

**Comment by MAKCOFF** [comment]
> Apparently this is a UEFI enabled secure boot issue. Take a look at the link: https://askubuntu.com/questions/1114867/operation-not-permitted-when-trying-to-modprobe-xpad

Many thanks! Indeed, that was the problem.
This after 
make -C /lib/modules/5.13.0-27-generic/build M=/home/maksim/tty0tty/module modules
make[1]: вход в каталог «/usr/src/linux-headers-5.13.0-27-generic»
make[1]: выход из каталога «/usr/src/linux-headers-5.13.0-27-generic»
echo "tty0tty" > /etc/modules-load.d/tty0tty.conf
cp 99-tty0tty.rules  /etc/udev/rules.d/
service udev reload
chown root:root /etc/udev/rules.d/99-tty0tty.rules
mkdir -p /lib/modules/5.13.0-27-generic/misc/
cp -v tty0tty.ko /lib/modules/5.13.0-27-generic/misc/
'tty0tty.ko' -> '/lib/modules/5.13.0-27-generic/misc/tty0tty.ko'
depmod
modprobe tty0tty
